### ISSUE TITLE
error DRM protected

### ISSUE THREAD

**Issue by Tecko71** [arnesongit/plugin.audio.tidal2#4]
On normal albums I got error DRM protected. MQA plays without a problem. Think has something to do witch device to choose

**Comment by Tecko71** [comment]
It has to do witch device to choose when choosing automotive no son will play. With selecting tv only MQA plays.

**Comment by arnesongit** [comment]
Which TIDAL apk version do you use ? The version number is shown in the headline of the device selector dialog.
TIDAL changes the client ids from time to time. The "Automotive" from the TIDAL apk version 2.36.1 until 2.64.2 should work. Please do not use a device type with "Dolby Atmos".

**Comment by Tecko71** [comment]
ohh I used 2.63.0

**Comment by Tecko71** [comment]
2.64.1 and 2.64.2 do not load, no device found in apk is the error. Only 2.63.0 works 2.63.1 en 2.63.2 I can not find

**Comment by arnesongit** [comment]
Sorry but since 2.64 the client ids are stored in a different place in the apk. I fixed it allready in my developer version.
Does it work with 2.63.0 for you ?
>> The next TIDAL2 version will be available soon. Then every device type will work, and TIDAL Free also ;-)

**Comment by Tecko71** [comment]
2.63.0 only MQA works when choosing TV. Automotive does not work at all. Drm error when it is no MQA

**Comment by arnesongit** [comment]
I allso tried it with TIDAL apk version 2.63.0 and the Automotive device type (the first in the list).
Everything is playing well for me. MQA, FLAC and AAC with quality "High".
Do you use Kodi on Windows ? What I found out is, that the HTTP streams with Kodi on Windows take a long time until start playing (up to 30 seconds). On my MacBook I have no problems with loading times or the HTTP streams.
Maybe this is a problem with the playback engine in Kodi for Windows. 
Please wait until the next version of TIDAL2 is ready. The other ClientIDs uses MPEG-Dash for streaming of FLAC and AAC. Then the addons inputstream.adaptive and inputstream.ffpmegdirect are used for playback and the streams are starting faster when using this addons.

**Comment by Tecko71** [comment]
I am running kodi matrix 19.4 on anrdroidTV. I installed inputstream but it is still the same when using automotive. I will wait till next release

**Comment by arnesongit** [comment]
I've released V2.1.1 which is unsing the inputstream addons for playback.
Please set the option "Use inputstream.ffmpegdirect as default player" in the addon settings if it isn't set automatically.
Then the playback should be startet immediately. I've tested it on a Raspberry Pi 4 running LineageOS 19 (Android 12).

**Comment by Tecko71** [comment]
> I've released V2.1.1 which is unsing the inputstream addons for playback. Please set the option "Use inputstream.ffmpegdirect as default player" in the addon settings if it isn't set automatically. Then the playback should be startet immediately. I've tested it on a Raspberry Pi 4 running LineageOS 19 (Android 12).

Yes this works on androidTV (shield) installed version Tidal 1.64.2 and choose automotive

**Comment by Tecko71** [comment]
question dolby atmos content. I can not search for dolby atmos genre. Where al the new albums are in Tidal. Explore gives also no option to dolby atmos content.

**Comment by arnesongit** [comment]
You can search for playlists with "Atmos" in its name.
TIDAL has no function to search for Atmos songs and albums.
